change notion.yml

diff --git a/.github/workflows/pages-deploy-notion.yml b/.github/workflows/pages-deploy-notion.yml
--- a/.github/workflows/pages-deploy-notion.yml
+++ b/.github/workflows/pages-deploy-notion.yml
@@ -83,6 +83,16 @@ jobs:
       # - name: Test site
       #   run: bundle exec htmlproofer _site --disable-external --check-html
 
+      - name: Debug - Check _site Directory
+        run: |
+          if [ -d "_site" ]; then
+            echo "✅ _site directory exists."
+            ls -lah _site
+          else
+            echo "❌ ERROR: _site directory is missing!"
+            exit 1
+          fi
+
       - name: Fix Invalid Filenames
         run: |
           find _site -name '*:*' | while read file; do
@@ -93,10 +103,11 @@ jobs:
         run: ls -lah _site  # Debugging step to check if _site exists
 
       - name: Upload site artifact
+        if: success()
         uses: actions/upload-artifact@v4
         with:
           name: github-pages
-          path: "_site"
+          path: _site
 
   deploy:
     environment:
@@ -105,6 +116,9 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Debug - List Available Artifacts
+        run: ls -lah ${{ github.workspace }}
+
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
